### ISSUE TITLE
Remove unneeded files.

### ISSUE THREAD

**Issue by Spicy-Axolotl** [ChessGeekBoy/Utilities#5]
Since creating the new VS .gitignore, I have noticed that so files in the .gitignore stayed in the repo and will need to remove manually later. I will probably do this over the weekend, however I wanted to make this an issue in case there is an automated way of doing this.

**Comment by ChessGeekBoy** [comment]
Sure, I'm facing tons of merge conflicts because of them and about half of our commits are becuase of them.

**Comment by Spicy-Axolotl** [comment]
Yeah this stuff needs to be fixed before it gets out of hand.
