### ISSUE TITLE
.NET build error.

### ISSUE THREAD

**Issue by Spicy-Axolotl** [ChessGeekBoy/Utilities#6]
The .NET workflow is failing due to these errors when running ```dotnet build --no-restore```
Please fix these errors so the workflow stops failing.
![image](https://user-images.githubusercontent.com/84357429/170809235-c744d10e-37b0-48a9-a7d2-540684e3142f.png)

**Comment by ChessGeekBoy** [comment]
Sure, I'll do that as soon as possible.
