### ISSUE TITLE
Path Regex

### ISSUE THREAD

**Issue by ChessGeekBoy** [ChessGeekBoy/Utilities#7]
As of now, ValidatePathAttribute's regular expression does not work as intended. It would say that `C:\Users\random\` is a proper path, but it would not say that `C:\Users\random` is proper. It would also say that `C:\Scripts\test.ps1` is an improper path.

**Comment by ChessGeekBoy** [comment]
Use https://regex101.com/ for testing the regex.

**Comment by ChessGeekBoy** [comment]
Something like C:/User\hi\ still works though.

**Comment by Spicy-Axolotl** [comment]
The regex ```^(([a-zA-Z]:|\\)\\)?(((\.)|(\.\.)|([^\\\/:\*\?"\|<>\. ](([^\\\/:\*\?"\|<>\. ])|([^\\\/:\*\?"\|<>]*[^\\\/:\*\?"\|<>\. ]))?))\\)*[^\\\/:\*\?"\|<>\. ](([^\\\/:\*\?"\|<>\. ])|([^\\\/:\*\?"\|<>]*[^\\\/:\*\?"\|<>\. ]))?$```
Matches with "c:\hi" and "c:\hi.ps1", but not "c:\hi\".

**Comment by Spicy-Axolotl** [comment]
It also labels "C:/User\hi\" as improper.

**Comment by Spicy-Axolotl** [comment]
The two current regex could be used in conjunction with one another. An example would be:
Regex ```^(([a-zA-Z]:|\\)\\)?(((\.)|(\.\.)|([^\\\/:\*\?"\|<>\. ](([^\\\/:\*\?"\|<>\. ])|([^\\\/:\*\?"\|<>]*[^\\\/:\*\?"\|<>\. ]))?))\\)*[^\\\/:\*\?"\|<>\. ](([^\\\/:\*\?"\|<>\. ])|([^\\\/:\*\?"\|<>]*[^\\\/:\*\?"\|<>\. ]))?$``` is checked then, <br>
Regex ```@"^(.+(\\|/))+$"``` is checked.

**Comment by ChessGeekBoy** [comment]
> 

That might not be ideal, it works in Windows File Explorer. Would you try something like that in Linux? Maybe something like
```
ls C:\Users/hi
```

**Comment by Spicy-Axolotl** [comment]
The regex I posted(the first one) works with both UNC (\\server\share\file) and regular MS path (c:\file).

**Comment by Spicy-Axolotl** [comment]
So yes, it should work in Linux.

**Comment by Spicy-Axolotl** [comment]
Working to add it in.

**Comment by Spicy-Axolotl** [comment]
Regex is done the new on is: ``^(([a-zA-Z]:|\\)\\)?(((\.)|(\.\.)|([^\\\/:\*\?""\|<>\. ](([^\\\/:\*\?""\|<>\. ])|([^\\\/:\*\?""\|<>]*[^\\\/:\*\?""\|<>\. ]))?))\\)*[^\\\/:\*\?""\|<>\. ](([^\\\/:\*\?""\|<>\. ])|([^\\\/:\*\?""\|<>]*[^\\\/:\*\?""\|<>\. ]))?$``. I think you can safely close this issue now.

**Comment by Spicy-Axolotl** [comment]
Closing this as it has been fixed.
